name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: check-if-index-html-exists
      id: check-if-index-html-exists
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: check-if-index-html-exists
        setup-command: ''
        command: ls index.html
        input: ''
        expected-output: index.html
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: check-if-table-tag-exists
      id: check-if-table-tag-exists
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: check-if-table-tag-exists
        setup-command: ''
        command: cat index.html
        input: ''
        expected-output: "<table>"
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: check-if-at-least-one-tr-tag-exists
      id: check-if-at-least-one-tr-tag-exists
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: check-if-at-least-one-tr-tag-exists
        setup-command: ''
        command: cat index.html
        input: ''
        expected-output: "<tr>"
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-IF-INDEX-HTML-EXISTS_RESULTS: "${{steps.check-if-index-html-exists.outputs.result}}"
        CHECK-IF-TABLE-TAG-EXISTS_RESULTS: "${{steps.check-if-table-tag-exists.outputs.result}}"
        CHECK-IF-AT-LEAST-ONE-TR-TAG-EXISTS_RESULTS: "${{steps.check-if-at-least-one-tr-tag-exists.outputs.result}}"
      with:
        runners: check-if-index-html-exists,check-if-table-tag-exists,check-if-at-least-one-tr-tag-exists
